### ISSUE TITLE
go-client panics on wrong credentials

### ISSUE THREAD

**Issue by ohait** [GoogleCloudPlatform/cloudsql-proxy#681]
## Question
After a missconfiguration (wrong username/password) the go library panics instead of returning a meaningful error.
I'm not sure if this is a bug on the client or on the proxy, hence this question.

## Additional Context
here the panic: 
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                   
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb2091b]                                                                                   
goroutine 1 [running]:                                                                                                                                    
github.com/go-sql-driver/mysql.(*mysqlConn).handleAuthResult(0xc000424000, 0xc0000385e0, 0x14, 0x14, 0xc0000385c0, 0x15, 0x0, 0x0)                        
 /home/oha/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/auth.go:376 +0x63b                                                                            
github.com/go-sql-driver/mysql.(*connector).Connect(0xc00030a000, 0xeb23c0, 0xc0000bc058, 0x0, 0x0, 0x0, 0x0)                                             
 /home/oha/go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connector.go:109 +0x5d8                                                                       
database/sql.(*DB).conn(0xc000370270, 0xeb23c0, 0xc0000bc058, 0xea6901, 0xc00030a000, 0x0, 0x0)                                                           
 /home/oha/sdk/go1.15.8/src/database/sql/sql.go:1294 +0x204                                                                                               
database/sql.(*DB).PingContext(0xc000370270, 0xeb23c0, 0xc0000bc058, 0x3d, 0xc000370270)                                                                  
 /home/oha/sdk/go1.15.8/src/database/sql/sql.go:799 +0x90                                                                                                 
database/sql.(*DB).Ping(...)                                                                                                                              
 /home/oha/sdk/go1.15.8/src/database/sql/sql.go:817
```
which matches
```
                    if pubKey == nil {
                        // request public key from server
                        data, err := mc.buf.takeSmallBuffer(4 + 1)
                        if err != nil {
                            return err
                        }
                        data[4] = cachingSha2PasswordRequestPublicKey
                        mc.writePacket(data)
                        // parse public key
                        if data, err = mc.readPacket(); err != nil {
                            return err
                        }
                        block, _ := pem.Decode(data[1:])
                        pkix, err := x509.ParsePKIXPublicKey(block.Bytes)
                        if err != nil {
                            return err
                        }
                        pubKey = pkix.(*rsa.PublicKey)
                    }
```
and it panics at `block.Bytes` which i read as no pem were returned from the proxy

I understand very little of all this, but i thought it was wise to share it here.

It took me a while to understand that the panic was wrong user/pass instead of something much worse

**Comment by shubha-rajan** [comment]
@ohait Thanks for opening the issue. From the code snippet you posted, it does look like the issue is that we're ignoring the error from `pem.Decode(data[1:])`. We'll work on pushing a patch shortly.

**Comment by kurtisvg** [comment]
It's helpful here if you can provide a minimal example to reproduce.

**Comment by ohait** [comment]
sorry for the confusion, it is indeed the mysql library. I will try to get a small example, but this is part of an automated deploy and i have limited access to the rest of the stack. What I know is that username and password were wrong, and it resulted in this error. Since it wasn't obvious about the wrong credential, it took me a while to understand the issue. I believe the bug is on the mysql drivers, but since it happens only with cloudsql-proxy and i don't know the internals, seemed smart to start here

**Comment by kurtisvg** [comment]
Thanks for following up @ohait - I'm going to mark this as closed. If it turns out there is something to be done on the proxy side let us know and we can reopen.
